xs:
    ip: 192.168.100.253
    username: root
    password: "123456"

ldap:
    ip: 192.168.1.211
    port: 389
    domain: xsvds.com

token:
    secret: ag5GaKL0CVmFI7t7x0xGaqdbRYf3JCdCXPc04OQsjV8=
